// flow-typed signature: f0d982f8fc37ab15bc7b0cde8fa17cd2
// flow-typed version: <<STUB>>/grommet-css_v^1.6.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grommet-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grommet-css' {
  declare module.exports: any;
}
