// flow-typed signature: f51ccaddf9d95db2ff19e4979e9083e3
// flow-typed version: <<STUB>>/grommet-templates_v^0.2.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grommet-templates'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grommet-templates' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grommet-templates/components/LayerForm' {
  declare module.exports: any;
}

declare module 'grommet-templates/grommet-templates.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grommet-templates/components/LayerForm.js' {
  declare module.exports: $Exports<'grommet-templates/components/LayerForm'>;
}
declare module 'grommet-templates/grommet-templates.min.js' {
  declare module.exports: $Exports<'grommet-templates/grommet-templates.min'>;
}
declare module 'grommet-templates/index' {
  declare module.exports: $Exports<'grommet-templates'>;
}
declare module 'grommet-templates/index.js' {
  declare module.exports: $Exports<'grommet-templates'>;
}
