// flow-typed signature: b34084bec27b2c56690f88c90dcf9abf
// flow-typed version: <<STUB>>/gzip-size_v3.0.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gzip-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gzip-size' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gzip-size/index' {
  declare module.exports: $Exports<'gzip-size'>;
}
declare module 'gzip-size/index.js' {
  declare module.exports: $Exports<'gzip-size'>;
}
