// flow-typed signature: 63c851cc5a9f794ecd2e2492d278264a
// flow-typed version: <<STUB>>/nielsbusch-grommet-css_v^1.8.3/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nielsbusch-grommet-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nielsbusch-grommet-css' {
  declare module.exports: any;
}
