// flow-typed signature: bc25878ebbf9d3b5a20928bfd4747aad
// flow-typed version: <<STUB>>/nielsbusch-grommet-css_v^1.9.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nielsbusch-grommet-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nielsbusch-grommet-css' {
  declare module.exports: any;
}
