// flow-typed signature: bc641cf27e66564db69ad85c0b86f7d7
// flow-typed version: <<STUB>>/path-exists_v2.1.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'path-exists'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'path-exists' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'path-exists/index' {
  declare module.exports: $Exports<'path-exists'>;
}
declare module 'path-exists/index.js' {
  declare module.exports: $Exports<'path-exists'>;
}
