// flow-typed signature: 54d2938173efff27f97964b0f387411e
// flow-typed version: <<STUB>>/redux-queue-offline_v^0.4.2/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-queue-offline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-queue-offline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-queue-offline/build/actions' {
  declare module.exports: any;
}

declare module 'redux-queue-offline/build/index' {
  declare module.exports: any;
}

declare module 'redux-queue-offline/build/initialState' {
  declare module.exports: any;
}

declare module 'redux-queue-offline/build/middleware' {
  declare module.exports: any;
}

declare module 'redux-queue-offline/build/reducer' {
  declare module.exports: any;
}

declare module 'redux-queue-offline/src/actions' {
  declare module.exports: any;
}

declare module 'redux-queue-offline/src/index' {
  declare module.exports: any;
}

declare module 'redux-queue-offline/src/initialState' {
  declare module.exports: any;
}

declare module 'redux-queue-offline/src/middleware' {
  declare module.exports: any;
}

declare module 'redux-queue-offline/src/reducer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-queue-offline/build/actions.js' {
  declare module.exports: $Exports<'redux-queue-offline/build/actions'>;
}
declare module 'redux-queue-offline/build/index.js' {
  declare module.exports: $Exports<'redux-queue-offline/build/index'>;
}
declare module 'redux-queue-offline/build/initialState.js' {
  declare module.exports: $Exports<'redux-queue-offline/build/initialState'>;
}
declare module 'redux-queue-offline/build/middleware.js' {
  declare module.exports: $Exports<'redux-queue-offline/build/middleware'>;
}
declare module 'redux-queue-offline/build/reducer.js' {
  declare module.exports: $Exports<'redux-queue-offline/build/reducer'>;
}
declare module 'redux-queue-offline/src/actions.js' {
  declare module.exports: $Exports<'redux-queue-offline/src/actions'>;
}
declare module 'redux-queue-offline/src/index.js' {
  declare module.exports: $Exports<'redux-queue-offline/src/index'>;
}
declare module 'redux-queue-offline/src/initialState.js' {
  declare module.exports: $Exports<'redux-queue-offline/src/initialState'>;
}
declare module 'redux-queue-offline/src/middleware.js' {
  declare module.exports: $Exports<'redux-queue-offline/src/middleware'>;
}
declare module 'redux-queue-offline/src/reducer.js' {
  declare module.exports: $Exports<'redux-queue-offline/src/reducer'>;
}
