// flow-typed signature: 709b2c196b29f3026a1b185939f3388f
// flow-typed version: <<STUB>>/redux-queue-offline-listener_v^0.2.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-queue-offline-listener'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-queue-offline-listener' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-queue-offline-listener/lib/native' {
  declare module.exports: any;
}

declare module 'redux-queue-offline-listener/lib/web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-queue-offline-listener/lib/native.js' {
  declare module.exports: $Exports<'redux-queue-offline-listener/lib/native'>;
}
declare module 'redux-queue-offline-listener/lib/web.js' {
  declare module.exports: $Exports<'redux-queue-offline-listener/lib/web'>;
}
