// flow-typed signature: 16ffa6ba935956e2979a9371d1c711a9
// flow-typed version: <<STUB>>/redux-queue-offline-listener_v^0.1.3/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-queue-offline-listener'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-queue-offline-listener' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-queue-offline-listener/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-queue-offline-listener/lib/index.js' {
  declare module.exports: $Exports<'redux-queue-offline-listener/lib/index'>;
}
