// flow-typed signature: 72801bf446095f37353efc7d3dfdaff1
// flow-typed version: <<STUB>>/rrule_v^2.2.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rrule'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rrule' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rrule/lib/nlp' {
  declare module.exports: any;
}

declare module 'rrule/lib/rrule' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rrule/lib/nlp.js' {
  declare module.exports: $Exports<'rrule/lib/nlp'>;
}
declare module 'rrule/lib/rrule.js' {
  declare module.exports: $Exports<'rrule/lib/rrule'>;
}
