// flow-typed signature: 8747e7ddef55abedeb3c30f7e7116552
// flow-typed version: <<STUB>>/stacktrace-js_v^2.0.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stacktrace-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stacktrace-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stacktrace-js/dist/stacktrace-with-promises-and-json-polyfills' {
  declare module.exports: any;
}

declare module 'stacktrace-js/dist/stacktrace-with-promises-and-json-polyfills.min' {
  declare module.exports: any;
}

declare module 'stacktrace-js/dist/stacktrace' {
  declare module.exports: any;
}

declare module 'stacktrace-js/dist/stacktrace.min' {
  declare module.exports: any;
}

declare module 'stacktrace-js/stacktrace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stacktrace-js/dist/stacktrace-with-promises-and-json-polyfills.js' {
  declare module.exports: $Exports<'stacktrace-js/dist/stacktrace-with-promises-and-json-polyfills'>;
}
declare module 'stacktrace-js/dist/stacktrace-with-promises-and-json-polyfills.min.js' {
  declare module.exports: $Exports<'stacktrace-js/dist/stacktrace-with-promises-and-json-polyfills.min'>;
}
declare module 'stacktrace-js/dist/stacktrace.js' {
  declare module.exports: $Exports<'stacktrace-js/dist/stacktrace'>;
}
declare module 'stacktrace-js/dist/stacktrace.min.js' {
  declare module.exports: $Exports<'stacktrace-js/dist/stacktrace.min'>;
}
declare module 'stacktrace-js/stacktrace.js' {
  declare module.exports: $Exports<'stacktrace-js/stacktrace'>;
}
